function buildApp() {
  const root = document.getElementById('app');
  if (!root) return;

  root.innerHTML = ''
    + '<div id="sidebar">'
    + '  <div class="sidebar-header">'
    + '    <div class="logo"><img src="' + LOGO_SRC + '" alt=""></div>'
    + '    <h1>' + APP_NAME + '</h1>'
    + '    <button class="restart-btn" id="restart-server-btn" title="重启服务"><span class="restart-icon">↻</span></button>'
    + '  </div>'
    + '  <button id="new-chat-btn"><span class="plus">+</span> 新对话</button>'
    + '  <div id="filter-bar">'
    + '    <button class="filter-btn active" data-filter="">全部</button>'
    + '    <button class="filter-btn" data-filter="pending">待办</button>'
    + '  </div>'
    + '  <div id="session-list"><div class="empty-state">加载中…</div></div>'
    + ''
    + '  <div id="agent-section">'
    + '    <div class="section-header" id="agent-section-toggle" role="button" tabindex="0">'
    + '      <span class="section-title">虾内助</span>'
    + '      <span class="section-count" id="agent-section-count"></span>'
    + '      <div class="section-actions">'
    + '        <button class="icon-btn new-agent-btn" id="new-agent-btn" title="新建助手">+</button>'
    + '      </div>'
    + '    </div>'
    + '    <div id="agent-list"></div>'
    + '  </div>'
    + '  <button id="sidebar-collapse-btn" title="折叠侧边栏">‹</button>'
    + '</div>'
    + ''
    + '<div id="sidebar-overlay"></div>'
    + '<button id="hamburger">'
    + '  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg>'
    + '</button>'
    + ''
    + '<div id="main">'
    + '  <div id="welcome"></div>'
    + '  <div id="messages" style="display:none">'
    + '    <div class="messages-inner"></div>'
    + '  </div>'
    + '  <div id="thinking-indicator" style="display:none">'
    + '    <span class="think-dot"></span>'
    + '    <span class="think-dot"></span>'
    + '    <span class="think-dot"></span>'
    + '  </div>'
    + '  <button id="scroll-bottom" title="回到底部">↓</button>'
    + '  <div id="input-area">'
    + '    <div id="attachment-bar"></div>'
    + '    <div class="input-wrap">'
    + '      <div class="input-row">'
    + '        <button class="attach-btn" id="attach-btn" title="上传附件（拖拽/粘贴/点击）">'
    + '          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.44 11.05l-9.19 9.19a6 6 0 01-8.49-8.49l9.19-9.19a4 4 0 015.66 5.66l-9.2 9.19a2 2 0 01-2.83-2.83l8.49-8.48"/></svg>'
    + '        </button>'
    + '        <textarea id="input" rows="1" placeholder="输入消息…  Enter 发送，Shift+Enter 换行"></textarea>'
    + '        <button id="send-btn" aria-label="发送">'
    + '          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>'
    + '        </button>'
    + '      </div>'
    + '      <div class="model-bar"></div>'
    + '    </div>'
    + '    <div class="drop-hint" style="display:none">释放以上传文件</div>'
    + '  </div>'
    + '</div>';
}
